spring.application.name = RecipeForge 

# H2
spring.datasource.url=${DB_URL:jdbc:h2:mem:recipeforge}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Openai
chatgpt.api.url:https://api.openai.com
api.key=${OPENAI_API_KEY}

# Gemini
gemini.api.key=${GEMINI_API_KEY}